language: rust
sudo: false
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

after_success:
  - cargo doc
  - curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh
