[package]
name = "qrcode"
description = "QR code encoder in Rust"
license = "Apache-2.0"
version = "0.1.7"
authors = ["kennytm <kennytm@gmail.com>"]
keywords = ["qrcode"]
repository = "https://github.com/kennytm/qrcode-rust"
readme = "README.md"
documentation = "http://kennytm.github.io/qrcode-rust/qrcode-rust/qrcode/"
exclude = [
    "scripts/*", ".travis.yml", ".gitignore"
]

[dependencies]
num = "0.1"

[features]
bench = []

[[bin]]
name = "qrencode"
