[package]
name = "qrcode"
description = "QR code encoder in Rust"
license = "MIT / Apache-2.0"
version = "0.2.1"
authors = ["kennytm <kennytm@gmail.com>"]
keywords = ["qrcode"]
repository = "https://github.com/kennytm/qrcode-rust"
readme = "README.md"
documentation = "http://docs.rs/qrcode"
exclude = [
    ".travis.yml", ".gitignore", "test-data"
]

[dependencies]
num-traits = "0.1.33"
image = { version = "0.12.1", optional = true }

[features]
default = ["image"]
bench = []

[[bin]]
name = "qrencode"
